excerpt_separator: "<!--more-->"
# pygments: true
highlighter: pygments
markdown: kramdown
url: https://shajiquan.github.io
title: Shajiquan's Island
tagline: 面朝大海，海风很冷。
description: ～～
paginate: 5
kramdown:
  input: GFM
  toc_levels:     1..6
  auto_ids: true
  footnote_nr: 1
gems:  [jekyll-paginate]
exclude: ["update.sh"]